// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "DiffValueSubjectExample",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "DiffValueSubjectExample",
            targets: ["AppModule"],
            bundleIdentifier: "jp.objective-audio.DiffValueSubjectExample",
            teamIdentifier: "WVVR5YE53F",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ]
        )
    ],
    dependencies: [
        .package(path: "../DiffValueSubjectExamples")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DiffValueSubjectExamples", package: "DiffValueSubjectExamples")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.v6]
)
